# Generated by Django 5.2.1 on 2025-06-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='fisrt_mame',
            new_name='first_mame',
        ),
    ]
